---
- name: Installs letsencrypt/certbot from snap.
  hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Install snapd.
    yum:
      name: snapd
      state: latest

  - name: Force systemd to re-read configs.
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start snapd.socket.
    ansible.builtin.systemd:
      name: snapd.socket
      enabled: yes
      state: started

  - name: Create symlink for snap classic support.
    ansible.builtin.file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link

  - name: Install snap core.
    community.general.snap:
      name: core

  - name: Install certbot from snap
    community.general.snap:
      name: certbot
      classic: true

  - name: Put certbot executabe in PATH.
    file:
      src: /snap/bin/certbot
      dest: /usr/bin/certbot
      state: link

  - name: Create TAK Server letsencrypt cert dir.
    file:
      path: /opt/tak/certs/files/letsencrypt
      state: directory

  - name: certbot | Generate standalone cert.
    ansible.builtin.command:
      argv:
        - certbot
        - certonly
        - --standalone
        - -m
        - certbot@undef.net
        - --agree-tos
        - -n
        - --domains
        - "{{ domain_name }}"
      creates: "/etc/letsencrypt/live/{{ domain_name }}"

  - name: export certs
    command:
      argv:
        - openssl
        - pkcs12
        - -export
        - -in
        - "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
        - -inkey
        - "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
        - -name
        - "{{ domain_name }}"
        - -out
        - "/opt/tak/certs/files/letsencrypt/{{ domain_name }}.p12"
        - -password
        - pass:atakatak
      creates: "/opt/tak/certs/files/letsencrypt/{{ domain_name }}.p12"

  - name: import keystore
    command:
      argv:
        - keytool
        - -importkeystore
        - -deststorepass
        - atakatak
        - -destkeystore
        - "/opt/tak/certs/files/letsencrypt/{{ domain_name }}.jks"
        - -srckeystore
        - "/opt/tak/certs/files/letsencrypt/{{ domain_name }}.p12"
        - -srcstoretype
        - PKCS12
        - -srcstorepass
        - atakatak
      creates: "/opt/tak/certs/files/letsencrypt/{{ domain_name }}.jks"

  - name: import bundle
    command:
      argv:
        - keytool
        - -noprompt
        - -import
        - -alias
        - bundle
        - -trustcacerts
        - -file
        - "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
        - -keystore
        - "/opt/tak/certs/files/letsencrypt/{{ domain_name }}.jks"
        - -storepass
        - atakatak

